### ISSUE TITLE
Inconsistent parameter types

### ISSUE THREAD

**Issue by Craigjw** [nghiand1010/Dapper.Contrib.Bulk#1]
The parameter types are inconsistent, some use IEnumerable<T> while others use List<T>

An example of this can be seen in SqlMapperExtensions.cs line 106:

```
public static void BulkDelete<T>(this IDbConnection connection, List<T> entities, IDbTransaction transaction = null, int? commandTimeout = null) where T : class
```

While most others use IEnumerable<T>, such as line 82, just above the previous example.
```
public static void BulkUpdate<T>(this IDbConnection connection, IEnumerable<T> entities, IDbTransaction transaction = null, int? commandTimeout = null) where T : class
```

Is it possible to update these to be more consistently and use either one or the other, but not both.  I would suggest changing them all to IEnumerable<T>.

Great work overall.

Thanks.

**Comment by nghiand1010** [comment]
Thank
I will fix that
